site_name: Curso HTML y CSS - 2º Bachillerato
site_description: Material didáctico completo para aprender HTML y CSS desde cero
site_author: Profesor TIC 2º Bachillerato
site_url: https://tu-usuario.github.io/curso-html-css/

theme:
  name: material
  language: es
  # navigation_depth: 2
  palette:
    # Modo claro
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Modo oscuro
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.numbered
    - navigation.indexes
    - navigation.breadcrumbs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    # - toc.integrate
    # - toc.numbered 
    - header.autohide
    - navigation.sections.collapsible
    - navigation.prev_next 
  font:
    text: Poppins, Sans
    code: Cascadia Code
  icon:
    repo: fontawesome/brands/github
 
plugins:
  - search:
      lang: es
  # - awesome-nav
  - enumerate-headings:
      toc_depth: 3
      strict: true
      increment_across_pages: true
      include:
        - "*"
      exclude:
        - index.md
        - another_page.md
      restart_increment_after:
        - ejercicios/introduccion-ejercicios.md
        - ejercicios-evaluables/1-html-basico-evaluable.md
        - proyecto/descripcion.md
        - recursos/html-cheatsheet.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # base_path: !relative  # Relative to the current Markdown file
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true
      baselevel: 1
      # numbered: true
      title: "En esta página"
      # separator: "_"
    

nav:
  - Presentación del curso: index.md
  
  - Teoría:
    - 1. Introducción: apuntes/01-introduccion.md
    - 2. HTML básico: apuntes/02-html-basico.md
    - 3. HTML semántico: apuntes/02-01-html-semantico.md
    - 4. HTML avanzado: apuntes/03-html-avanzado.md
    - 04. CSS Fundamentos: apuntes/04-css-fundamentos.md
    - 04.01. CSS Efectos: apuntes/04-01-css-efectos.md
    - 05. CSS Layout: 
      - 05.00. Introducción al Layout: apuntes/05-00-css-layout.md
      - 05.01. Display: apuntes/05-01-css-layout-display.md
      - 05.02. Position: apuntes/05-02-css-layout-position.md
      - 05.03. Flexbox: apuntes/05-03-css-layout-flexbox.md
      - 05.04. Grid: apuntes/05-04-css-layout-grid.md
    - 06. Diseño adaptable (Media queries): apuntes/06-responsive.md


  - Ejercicios resueltos:
    - Introducción Ejercicios: ejercicios/introduccion-ejercicios.md
    - HTML Básico: ejercicios/html-basico.md
    - HTML Avanzado: ejercicios/html-avanzado.md
    - CSS Básico: ejercicios/css-basico.md
    - CSS Avanzado:
      - CSS Flexbox: ejercicios/css-flexbox.md
      - CSS Grid: ejercicios/css-grid.md
  
  - Ejercicios evaluables:
    - 1. HTML Básico (evaluable): ejercicios-evaluables/1-html-basico-evaluable.md
    - 2. HTML Semántico (evaluable): ejercicios-evaluables/2-html-semantico-evaluable.md

  - Proyecto Web:
    - Descripción General: proyecto/descripcion.md
  
  - Recursos:
    - Cheatsheet HTML: recursos/html-cheatsheet.md
    - Cheatsheet CSS: recursos/css-cheatsheet.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tu-usuario
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:profesor@ejemplo.com
      name: Contacto

copyright: Copyright &copy; 2025 - Curso HTML y CSS 2º Bachillerato TIC

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
